[package]
name = "frac"
version = "0.1.0"
authors = ["Travis Geiselbrecht <travisg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.33"
